apiVersion: v1
kind: ReplicationController
metadata:
  name: web2
spec:
  replicas: 3
  selector:
    app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: ibo6m/nginx_web
        ports:
        - containerPort: 8080
