apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ibo6m/nginx_web
