apiVersion: v1
kind: Service
metadata:
  name: fortune-args
spec:
  type: NodePort
  ports:
  - port: 8080          # cluster-IP's port.
    targetPort: 80
    nodePort: 30124   # accessible through port 30123 of cluster nodes.
  selector:
    app: fortune-args

